Update to GoCSI 0.3.1

diff --git a/vendor/github.com/thecodeteam/gocsi/Makefile b/vendor/github.com/thecodeteam/gocsi/Makefile
--- a/vendor/github.com/thecodeteam/gocsi/Makefile
+++ b/vendor/github.com/thecodeteam/gocsi/Makefile
@@ -20,19 +20,13 @@ export GOPATH
 ##                                   DEP                                      ##
 ################################################################################
 DEP ?= ./dep
-DEP_VER ?= 0.3.2
-DEP_BIN := dep-$$GOHOSTOS-$$GOHOSTARCH
-DEP_URL := https://github.com/golang/dep/releases/download/v$(DEP_VER)/$$DEP_BIN
+DEP_DIR := ./vendor/github.com/golang/dep
 
 $(DEP):
-	GOVERSION=$$(go version | awk '{print $$4}') && \
-	GOHOSTOS=$$(echo $$GOVERSION | awk -F/ '{print $$1}') && \
-	GOHOSTARCH=$$(echo $$GOVERSION | awk -F/ '{print $$2}') && \
-	DEP_BIN="$(DEP_BIN)" && \
-	DEP_URL="$(DEP_URL)" && \
-	curl -sSLO $$DEP_URL && \
-	chmod 0755 "$$DEP_BIN" && \
-	mv -f "$$DEP_BIN" "$@"
+	@rm -fr $(DEP_DIR)
+	git clone https://github.com/akutz/dep $(DEP_DIR)
+	git -C $(DEP_DIR) checkout feature/fetch-gh-pulls
+	go build -o $@ $(DEP_DIR)/cmd/dep
 
 ifneq (./dep,$(DEP))
 dep: $(DEP)
@@ -57,11 +51,6 @@ $(CONTEXT_A): context/*.go
 	@go install ./$(basename $(@F))
 	go build -o "$@" ./$(basename $(@F))
 
-ERRORS_A := errors.a
-$(ERRORS_A): errors/*.go
-	@go install ./$(basename $(@F))
-	go build -o "$@" ./$(basename $(@F))
-
 MIDDLEWARE_PKGS := $(addsuffix .a,$(filter-out %.a,$(wildcard middleware/*)))
 $(MIDDLEWARE_PKGS): %.a: $(wildcard %/*.go)
 	@go install ./middleware/$(basename $(@F))
@@ -74,7 +63,7 @@ $(UTILS_A): utils/*.go
 	@go install ./$(basename $(@F))
 	go build -o "$@" ./$(basename $(@F))
 
-GOCSI_A_PKG_DEPS := $(CONTEXT_A) $(ERRORS_A) $(MIDDLEWARE_PKGS) $(UTILS_A)
+GOCSI_A_PKG_DEPS := $(CONTEXT_A) $(MIDDLEWARE_PKGS) $(UTILS_A)
 
 GOCSI_A := gocsi.a
 $(GOCSI_A): $(CSI_GOSRC) *.go $(GOCSI_A_PKG_DEPS)
@@ -90,8 +79,14 @@ CSI_SP_DIR := $(GOPATH)/src/$(CSI_SP_IMPORT)
 CSI_SP := $(CSI_SP_DIR)/csi-sp
 CSI_SP_SOCK := $(notdir $(CSI_SP)).sock
 CSI_SP_LOG := $(notdir $(CSI_SP)).log
-$(CSI_SP):
-	USE_DEP=true ./gocsi.sh $(CSI_SP_IMPORT)
+GOCSI_SH_ENV := USE_DEP=true
+GOCSI_SH_ENV += DEP_GIT_REFSPECS=+refs/pull/*:refs/pull/origin/*
+ifeq (true,$(TRAVIS))
+GOCSI_SH_ENV += GOCSI_DEP_SOURCE=https://github.com/$(TRAVIS_REPO_SLUG)
+GOCSI_SH_ENV += GOCSI_DEP_REVISION=$(TRAVIS_COMMIT)
+endif
+$(CSI_SP): | $(DEP)
+	DEP=$(abspath $(DEP)) $(GOCSI_SH_ENV) ./gocsi.sh $(CSI_SP_IMPORT)
 
 csi-sp: $(CSI_SP_LOG)
 $(CSI_SP_LOG): $(CSI_SP)
@@ -120,7 +115,7 @@ $(CSI_SP_LOG): $(CSI_SP)
 	  printf '=%.0s' $$(seq 1 80) && printf '\n== ' && \
 	  printf "%-74s" "invoking GetPluginInfo" && printf ' ==\n' && \
 	  printf '=%.0s' $$(seq 1 80) && echo
-	csc/csc -e $(CSI_SP_SOCK) i info
+	csc/csc -e $(CSI_SP_SOCK) i info -v 0.1.0
 	@echo && \
 	  printf '=%.0s' $$(seq 1 80) && printf '\n== ' && \
 	  printf "%-74s" "killing $(<F) with SIGINT" && printf ' ==\n' && \
@@ -148,8 +143,13 @@ ifeq (true,$(TRAVIS))
 GINKGO_SECS := 30
 endif
 GINKGO_RUN_OPTS := --slowSpecThreshold=$(GINKGO_SECS) -randomizeAllSpecs -p
-$(GINKGO):
-	go build -o "$@" $(GINKGO_PKG)
+$(GINKGO): | $(GINKGO_PKG)
+	go build -o "$@" "./$|"
+
+ETCD := ./etcd
+$(ETCD):
+	go get -u -d github.com/coreos/etcd
+	go build -o $@ github.com/coreos/etcd
 
 # The test recipe executes the Go tests with the Ginkgo test
 # runner. This is the reason for the boolean OR condition
@@ -162,27 +162,24 @@ test:  build
 endif
 
 # Because Travis-CI's containers have limited resources, the Mock SP's
-# idempotency provider's timeout needs to be increased from the default
-# value of 0 to 1s. This ensures that lack of system resources will not
-# prevent a single, non-concurrent RPC from failing due to an OpPending
-# error.
+# serial volume access provider's timeout needs to be increased from the
+# default value of 0 to 3s. This ensures that lack of system resources
+# will not prevent a single, non-concurrent RPC from failing due to an
+# OpPending error.
 ifeq (true,$(TRAVIS))
-export X_CSI_IDEMP_TIMEOUT=1s
+export X_CSI_SERIAL_VOL_ACCESS_TIMEOUT=3s
 endif
 
-test: | $(GINKGO)
+test: | $(GINKGO) $(ETCD)
 	$(GINKGO) $(GINKGO_RUN_OPTS) ./utils || test "$$?" -eq "197"
-	$(GINKGO) $(GINKGO_RUN_OPTS) ./testing || test "$$?" -eq "197"
-
-
-########################################################################
-##                               BENCH                                ##
-########################################################################
-ifneq (true,$(TRAVIS))
-bench: build
-endif
-bench:
-	go test -run Bench -bench . -benchmem . || test "$$?" -eq "197"
+	@rm -fr default.etcd etcd.log
+	./etcd > etcd.log 2>&1 &
+	X_CSI_SERIAL_VOL_ACCESS_ETCD_ENDPOINTS=127.0.0.1:2379 \
+	  $(GINKGO) $(GINKGO_RUN_OPTS) -skip "Idempotent Create" \
+	  ./testing || test "$$?" -eq "197"
+	pkill etcd
+	$(GINKGO) $(GINKGO_RUN_OPTS) -focus "Idempotent Create" \
+	  ./testing || test "$$?" -eq "197"
 
 
 ########################################################################
